import { GradePoints, SemesterCourses } from './types';

export const GRADE_OPTIONS: string[] = ['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'D', 'F', 'N/A'];

export const GRADE_POINTS: GradePoints = {
  'A+': 4.0,
  'A': 3.75,
  'A-': 3.5,
  'B+': 3.25,
  'B': 3.0,
  'B-': 2.75,
  'C+': 2.5,
  'C': 2.25,
  'D': 2.0,
  'F': 0.0,
  'N/A': 0.0,
};

export const SEMESTER_COURSES: SemesterCourses = {
  '1.1': [
    { code: 'EEE101', name: 'Electrical Circuits I', credits: 3 },
    { code: 'EEE102', name: 'Electrical Circuits I Lab', credits: 1.5 },
    { code: 'MAT105', name: 'Engineering Mathematics I', credits: 3 },
    { code: 'MAT107', name: 'Engineering Mathematics II', credits: 3 },
    { code: 'ENG105', name: 'Technical English', credits: 2 },
    { code: 'ENG106', name: 'Technical English Lab', credits: 1 },
    { code: 'PHY115', name: 'Physics I', credits: 3 },
    { code: 'PHY116', name: 'Physics I Lab', credits: 0.75 },
    { code: 'CE126', name: 'Engineering Drawing', credits: 1 },
  ],
  '1.2': [
    { code: 'EEE151', name: 'Electrical Circuit II', credits: 3 },
    { code: 'EEE152', name: 'Electrical Circuit II Lab', credits: 1.5 },
    { code: 'MAT157', name: 'Engineering Mathematics III', credits: 3 },
    { code: 'PHY165', name: 'Physics II', credits: 2 },
    { code: 'STA167', name: 'Statistics for Engineers', credits: 3 },
    { code: 'CHE185', name: 'Chemistry', credits: 3 },
    { code: 'CHE186', name: 'Chemistry Lab', credits: 0.75 },
    { code: 'CSE195', name: 'Programming Language', credits: 3 },
    { code: 'CSE196', name: 'Programming Language Lab', credits: 1.5 },
  ],
  '2.1': [
    { code: 'EEE202', name: 'Electrical Service Design', credits: 0.75 },
    { code: 'EEE211', name: 'Electronics I', credits: 3 },
    { code: 'EEE212', name: 'Electronics I Lab', credits: 1.5 },
    { code: 'EEE231', name: 'Electrical Machine I', credits: 3 },
    { code: 'EEE232', name: 'Electrical Machine I Lab', credits: 1.5 },
    { code: 'ME205', name: 'Mechanical Engineering Fundamentals', credits: 3 },
    { code: 'ME206', name: 'Mechanical Engineering Fundamentals Lab', credits: 0.75 },
    { code: 'MAT205', name: 'Engineering Mathematics IV', credits: 3 },
    { code: 'AIS215', name: 'Industrial Management and Accountancy', credits: 2 },
  ],
  '2.2': [
    { code: 'EEE250', name: 'Electrical and Electronic Circuit Simulation Lab', credits: 1.5 },
    { code: 'EEE251', name: 'Measurement and Instrumentation', credits: 3 },
    { code: 'EEE252', name: 'Measurement and Instrumentation Lab', credits: 0.75 },
    { code: 'EEE261', name: 'Electronics II', credits: 3 },
    { code: 'EEE262', name: 'Electronics II Lab', credits: 1.5 },
    { code: 'EEE271', name: 'Electrical Machine II', credits: 3 },
    { code: 'EEE272', name: 'Electrical Machine II Lab', credits: 1.5 },
    { code: 'EEE281', name: 'Electromagnetics', credits: 3 },
    { code: 'MAT257', name: 'Engineering Mathematics V', credits: 3 },
  ],
  '3.1': [
    { code: 'EEE301', name: 'Signals and Linear Systems', credits: 3 },
    { code: 'EEE309', name: 'Project', credits: 0.75 },
    { code: 'EEE311', name: 'Digital Electronics', credits: 3 },
    { code: 'EEE312', name: 'Digital Electronics Lab', credits: 1.5 },
    { code: 'EEE321', name: 'Power Electronics', credits: 3 },
    { code: 'EEE322', name: 'Power Electronics Lab', credits: 1.5 },
    { code: 'EEE341', name: 'Numerical Methods for Engineering', credits: 3 },
    { code: 'EEE342', name: 'Numerical Methods for Engineering Lab', credits: 1.5 },
    { code: 'BLB305', name: 'Bangabandhu in Engineering and Professional Ethics', credits: 2 },
    { code: 'ECO307', name: 'Economics', credits: 2 },
  ],
  '3.2': [
    { code: 'EEE361', name: 'Communication Theory', credits: 4 },
    { code: 'EEE362', name: 'Communication Theory Lab', credits: 1.5 },
    { code: 'EEE363', name: 'Electronic circuit for communication system', credits: 2 },
    { code: 'EEE369', name: 'Industrial Training', credits: 0.75 },
    { code: 'EEE371', name: 'Control System', credits: 3 },
    { code: 'EEE372', name: 'Control System Lab', credits: 1.5 },
    { code: 'EEE381', name: 'Microprocessor, Interfacing and System design', credits: 3 },
    { code: 'EEE382', name: 'Microprocessor, Interfacing and System design Lab', credits: 1.5 },
    { code: 'EEE391', name: 'Power System I', credits: 3 },
    { code: 'EEE392', name: 'Power System I Lab', credits: 1.5 },
  ],
  '4.1': [
    { code: 'EEE409', name: 'Project and Thesis', credits: 1 },
    { code: 'EEE401', name: 'Digital Signal Processing', credits: 3 },
    { code: 'EEE402', name: 'Digital Signal Processing Lab', credits: 1.5 },
    { code: 'EEE411', name: 'Power System Protection', credits: 3 },
    { code: 'EEE412', name: 'Power System Protection Lab', credits: 1.5 },
    { code: 'EEE421', name: 'Power System II', credits: 3 },
    { code: 'EEE422', name: 'Power System II Lab', credits: 1.5 },
    { code: 'EEE423', name: 'High Voltage Engineering', credits: 3 },
    { code: 'EEE413', name: 'Electrical Properties of Materials', credits: 3 },
  ],
  '4.2': [
    { code: 'EEE459', name: 'Project and Thesis', credits: 3 },
    { code: 'EEE491', name: 'Microcontroller and PLC based System Design', credits: 3 },
    { code: 'EEE492', name: 'Microcontroller and PLC based System Design Lab', credits: 1.5 },
    { code: 'EEE461', name: 'VLSI', credits: 3 },
    { code: 'EEE462', name: 'VLSI Lab', credits: 1.5 },
    { code: 'EEE471', name: 'Non-Conventional Energy', credits: 3 },
    { code: 'EEE472', name: 'Non-Conventional Energy Lab', credits: 0.75 },
    { code: 'EEE473', name: 'Power Plant Engineering and Economy', credits: 3 },
  ],
};